/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/hexagon.glb -o src/components/Hexagon.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

const Hexagon = ({ color, ...props }) => {
  const { nodes, materials } = useGLTF("/models/hexagon.glb", "draco/gltf/");

  return (
    <group {...props}>
      <mesh geometry={nodes.Hexagon.geometry} material={materials.hexagon}>
        <meshStandardMaterial
          {...materials.hexagon}
          color={color}
          transparent
        />
      </mesh>
    </group>
  );
};

export default Hexagon;

useGLTF.preload("/models/hexagon.glb", "draco/gltf/");
